language: python
python:
  - 2.7
addons:
  apt:
    packages:
    - gfortran
before_script:
  - make
script:
  - make test

notifications:
  email: true

# Branches to be built
branches:
  only:
    - master
    - 2d
