language: c
before_install:
  - |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt-get update -q
    sudo apt-get install gcc-5 --force-yes
    sudo apt-get install gfortran-5 --force-yes
    export FC=gfortran-5
    $FC --version
script:
  make test -e
branches:
  only:
    - master
notifications:
  email:
    on_success: change # default: change (send a notification when the build status changes)
    on_failure: never # default: always
