language: python
python:
  - 2.7
before_install:
  - sudo apt-get install gfortran liblapack-dev
before_script:
  - make
script:
  - make test

notifications:
  email: true

# Branches to be built
branches:
  only:
    - master
    - 2d
